// <auto-generated />
using System;
using Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Migrations;

[DbContext(typeof(GroundedDbContext))]
[Migration("20260920220000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12");

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.FoodRecord",
            b =>
            {
                b.Property<Guid>("FoodId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("SpoilsAtUtc")
                    .HasColumnType("TEXT");

                b.Property<int>("State")
                    .HasColumnType("INTEGER");

                b.HasKey("FoodId");

                b.ToTable("Foods");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.InventoryItemRecord",
            b =>
            {
                b.Property<Guid>("PlayerId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("ItemId")
                    .HasColumnType("TEXT");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.HasKey(
                    "PlayerId",
                    "ItemId");

                b.ToTable("InventoryItems");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.InventoryRecord",
            b =>
            {
                b.Property<Guid>("PlayerId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.HasKey("PlayerId");

                b.ToTable("Inventories");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.RecipeIngredientRecord",
            b =>
            {
                b.Property<Guid>("RecipeId")
                    .HasColumnType("TEXT");

                b.Property<int>("Position")
                    .HasColumnType("INTEGER");

                b.Property<Guid>("ItemId")
                    .HasColumnType("TEXT");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.HasKey(
                    "RecipeId",
                    "Position");

                b.ToTable("RecipeIngredients");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.RecipeRecord",
            b =>
            {
                b.Property<Guid>("RecipeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<Guid>("ResultItemId")
                    .HasColumnType("TEXT");

                b.Property<int>("ResultQuantity")
                    .HasColumnType("INTEGER");

                b.HasKey("RecipeId");

                b.ToTable("Recipes");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.InventoryItemRecord",
            b =>
            {
                b.HasOne(
                        "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.InventoryRecord",
                        "Inventory")
                    .WithMany("Items")
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Inventory");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.RecipeIngredientRecord",
            b =>
            {
                b.HasOne(
                        "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.RecipeRecord",
                        "Recipe")
                    .WithMany("Ingredients")
                    .HasForeignKey("RecipeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Recipe");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.InventoryRecord",
            b =>
            {
                b.Navigation("Items");
            });

        modelBuilder.Entity(
            "Grounded.Hexagonal.Adapters.Outbound.Persistence.EntityFrameworkCore.Models.RecipeRecord",
            b =>
            {
                b.Navigation("Ingredients");
            });

#pragma warning restore 612, 618
    }
}
